### ISSUE TITLE
only SQL JSON and YAML are counted

### ISSUE THREAD

**Issue by toxazol** [uctakeoff/vscode-counter#18]
![image](https://user-images.githubusercontent.com/19937990/71993501-e1275080-323f-11ea-97be-e8a0cbb1ec50.png)
![image](https://user-images.githubusercontent.com/19937990/71993518-e7b5c800-323f-11ea-94cd-b3007d37c718.png)

**Comment by uctakeoff** [comment]
You can see a detailed log of this extension in the developer tools.

`Help> Toggle Developer Tools`

Please tell me what was output.

**Comment by dan-1d** [comment]
Similar issue:  "count lines in directory" seems to skip the .json files I have there" .json is not in the "exclude list". Output reports do not list any JSON lines, even though there are many .json files.

[Extension Host] [VSCodeCounter] 2020-06-29T23:42:39.659Z excludes : "**/.gitignore", "**/.vscode/**", "**/node_modules/**", "**/.git", "**/.svn", "**/.hg", "**/CVS", "**/.DS_Store", ".VSCodeCounter", "**/.git", "**/.svn", "**/.hg", "**/CVS", "**/.DS_Store", ".VSCodeCounter", "**/.git", "**/.svn", "**/.hg", "**/CVS", "**/.DS_Store", ".VSCodeCounter", "**/.git", "**/.svn", "**/.hg", "**/CVS", "**/.DS_Store", ".VSCodeCounter"

**Comment by uctakeoff** [comment]
@toxazol 

Ver. 2.0.0 released.

Previously, the VSCode Counter did not work properly with *Remote Development* due to implementation issues.
This time, I have implemented an experimental workaround for this issue.

Please try the following;
* First, launch VSCode on your local.
* Then, open the command palette and select  `VSCodeCounter: Save the collected language configurations`.
* Then *settings.json* will store the configuration information collected from the current language extensions .
* Connect to the remote (after updating the remote's VSCodecounter) and use it as usual.
