### ISSUE TITLE
Javascript and Typescript not working with Remote-SSH

### ISSUE THREAD

**Issue by RDMStreet** [uctakeoff/vscode-counter#20]
My whole project is written in typescript and VSCodeCounter ignores all .ts files.This is relevant only when I connect to a remote directory using Remote-SSH.

**Comment by uctakeoff** [comment]
You can see a detailed log of this extension in the developer tools.

`Help> Toggle Developer Tools`

Please tell me what was output.

**Comment by uctakeoff** [comment]
I replaced the file API used with one provided by vscode.
Ver.1.3.2. Perhaps this does not help?

**Comment by RDMStreet** [comment]
![Screenshot_115](https://user-images.githubusercontent.com/8494787/74081977-ff15ea00-4a65-11ea-9ab9-7e267e55ec30.png)

**Comment by uctakeoff** [comment]
Could you try the following:

* Open the command palette and select  `VSCodeCounter: Check available languages`.
* Check "VSCode Counter: Ignore Unsupported File" in the settings and count again.

**Comment by RDMStreet** [comment]
![Screenshot_116](https://user-images.githubusercontent.com/8494787/74084797-b10fdf00-4a83-11ea-943f-78633d1993bb.png)
![Screenshot_118](https://user-images.githubusercontent.com/8494787/74084799-b3723900-4a83-11ea-88a9-d930d47d0a1c.png)
![Screenshot_117](https://user-images.githubusercontent.com/8494787/74084800-b5d49300-4a83-11ea-9f25-d37259731182.png)

**Comment by uctakeoff** [comment]
Looks like the TypeScript language extension is missing.
If found, you should see something like:
![2020-02-08](https://user-images.githubusercontent.com/25006799/74085522-ff8d9f80-4abc-11ea-8211-4040cc9f9f9b.png)

It seems to be because Remote-SSH is used, but I do not know the exact cause.
Usually it should be installed from the beginning.

I'm not sure because I've never used Remote-SSH, but have you noticed anything from this story?

**Comment by luckyray-fan** [comment]
Oh, i have the same issue, in remote-ssh.
file cannot be found except EditorConfig and json (my project is base on react and typescript)

**Comment by uctakeoff** [comment]
As I mentioned elsewhere, I have found that VSCodeCounter does not work properly with "VSCode Remote Development".

VSCodeCounter can also count for unknown languages by referring to information in your installed language extensions.
However, this information is not available in "Remote Development".

We are currently working through a trial and error process to find a solution.
Please wait for a while.

**Comment by uctakeoff** [comment]
@RDMStreet @luckyray-fan 

Ver. 2.0.0 released.

I modified VSCode Counter's ability to **collecting VSCode language extensions** so that it can be called as an independent function. The idea is to collect the information once in the local environment and store it so that it can be used remotely.

Please try the following;
* First, launch VSCode on your local.
* Then, open the command palette and select  `VSCodeCounter: Save the collected language configurations`.
* Then *settings.json* will store the configuration information collected from the current language extensions .
* Connect to the remote (after updating the remote's VSCodecounter) and use it as usual.

**Comment by luckyray-fan** [comment]
success, thanks for your work
![image](https://user-images.githubusercontent.com/38815993/86730715-6a89d500-c061-11ea-889b-c87712ae3e19.png)

**Comment by RDMStreet** [comment]
I still have problems with this.
![image](https://user-images.githubusercontent.com/8494787/87220474-b80d8700-c36c-11ea-812d-f1509a719e0f.png)

**Comment by plus5170** [comment]
I found a problem that it only works for my home folder /home/XXX. 
In fact, I use the /data/XXX folder more frequently, is there any solutions?

**Comment by uctakeoff** [comment]
@plus5170 
I'm sorry. I'm not sure what's going on.
My English is not very good, so it would be helpful if you could explain it to me.

* Is that what happened with Remote-SSH?
* Is "/home/" the Unix filesystem's home directory?
* What kind of files are in "/data/"?
* What kind of output do you expect to get when you run `VSCodeCounter: Count lines in workspace` with this setting `VSCode Counter: Ignore Unsupported File` enabled?
* What kind of output do I get when I run a `VSCodeCounter: Check available languages` with the setting enabled?

Translated with www.DeepL.com/Translator (free version)

**Comment by plus5170** [comment]
> @plus5170
> I'm sorry. I'm not sure what's going on.
> My English is not very good, so it would be helpful if you could explain it to me.
> 
> * Is that what happened with Remote-SSH?
> * Is "/home/" the Unix filesystem's home directory?
> * What kind of files are in "/data/"?
> * What kind of output do you expect to get when you run `VSCodeCounter: Count lines in workspace` with this setting `VSCode Counter: Ignore Unsupported File` enabled?
> * What kind of output do I get when I run a `VSCodeCounter: Check available languages` with the setting enabled?
> 
> Translated with [www.DeepL.com/Translator](http://www.DeepL.com/Translator) (free version)

I'm sorry I wasn't clear.
I use Remote-SSH to open folders on my linux sever and "/home/w5yl" is my remote home folder. I have some codes in my home folder, but most of my code is in "/data/w5yl". 
The problem is the command ```VSCodeCounter: Count lines in workspace``` only worked on "/home/w5yl" but didn't work on "/data/w5yl".
Then I found that the count failed because there were too many files in the "/data/w5yl" directory. After setting the ```VSCodeCounter: Include``` option, I got the count results. It turns out the new version of the extension works well with Remote-SSH.
Thanks for your reply!! Useful extension!
