### ISSUE TITLE
Is it possible to activate realtime counter visibility on start?

### ISSUE THREAD

**Issue by Tosh0kan** [uctakeoff/vscode-counter#66]
Is there config option or method to make the command to toggle real-time counter visibility automatically on start?

**Comment by uctakeoff** [comment]
In fact, it used to be implemented that way.
However, in order to make it work, the extension needs to be resident. Resident extensions are loaded even when they are not running, consuming memory.
I was pointed this out before.
I fixed it, and now it requires an explicit call.

I have not found a better way to do this.

**Comment by johan-maes-sword** [comment]
I'd also be interested in this. I tried looking for a workaround, ie run the toggle command at startup but that doesn't seem to be possible right now.

**Comment by uctakeoff** [comment]
It's too late now, but ver. 3.3.0 supports it on a trial basis.
Check it out.
